{{- if .Values.nginx.enable }}
apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.port }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: nginx
{{- end }}