{{- if .Values.nginx.enable }}
apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30895
      protocol: TCP
      name: http
  selector:
    app: nginx
{{- end }}